# Generated by Django 3.1.5 on 2021-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phno', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
